backend:
  name: github
  repo: jonasz-kalina/factory-website
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "home"
    label: "Strona główna"
    files:
      - file: "data/home.json"
        label: "Home"
        name: "home"
        fields:
          - { label: "Tytuł", name: "title", widget: "string" }
          - { label: "Opis", name: "description", widget: "text" }